#!/bin/sh

################################################################################
# vob2mp4 - convert all VOB files in directory to MP4                          #
# v0.1.5                                                                       #
# David RC Dayton <2014>                                                       #
################################################################################
#               NOTE: requires mplayer (compiled with aac), mencoder, and gpac #
################################################################################

WIDTH="720"
HEIGHT="480"
VBITRATE="800"
ABITRATE="128"
FPS="24000/1001"
SAMPLE="44100"
SS="60"
ENDPOS="1800"
ASPECT="16/9"

for FILE in *.vob
do
    BASE=$(echo ${FILE} | awk -F '.' '{print $1}')
    INPUT=${BASE}.vob
    OUTPUT=${BASE}.avi
    BOXED=${BASE}.mp4
    echo Processing ${INPUT}:

    echo Detecting crop parameters....
    CROP=$(mplayer ${INPUT} -benchmark -nosound -vf cropdetect=63:0 -vo null \
        -ao null -ss ${SS} -endpos ${ENDPOS} 2>&1 \
        | awk -F '[(=)]' '/crop=/ {print $3}' \
        | tail -1)
      
    echo Encoding ${INPUT} to ${OUTPUT}:
    mencoder ${INPUT} -ovc x264 -x264encopts \
    bitrate=${VBITRATE}:subq=6:partitions=all:8x8dct:me=umh:frameref=5:bframes=3:b_pyramid=normal:weight_b \
    -vf pp=lb,crop=${CROP},scale=${WIDTH}:${HEIGHT},harddup -nosub \
    -oac faac -faacopts br=${ABITRATE}:object=2:tns \
    -aid 128 -af volnorm,resample=${SAMPLE}:0:2 -srate ${SAMPLE} \
    -ofps ${FPS} -sws 9 -aspect ${ASPECT} -o ${OUTPUT} "$@"

    MP4Box -aviraw video ${OUTPUT}
    MP4Box -aviraw audio ${OUTPUT}
    mv ${BASE}_audio.raw ${BASE}_audio.aac
    MP4Box -add ${BASE}_video.h264 -add ${BASE}_audio.aac -isma ${BOXED}
      
    rm ${OUTPUT}
    rm ${BASE}_video.h264 ${BASE}_audio.aac
done

