#!/bin/sh

################################################################################
# vob2avi - convert all VOB files in directory to MKV                          #
# v0.1.7                                                                       #
# David RC Dayton <2014>                                                       #
################################################################################
#            NOTE: requires mplayer/mencoder/mkvtoolnix/normalize-audio/mpg321 #
################################################################################

WIDTH="720"
HEIGHT="480"
VBITRATE="800"
ABITRATE="128"
FPS="24000/1001"
SAMPLE="44100"
SS="60"
ENDPOS="1800"

for FILE in *.vob
do
    BASE=$(echo ${FILE} | awk -F '.' '{print $1}')
    INPUT=${BASE}.vob
    OUTPUT=${BASE}.mkv
    echo Processing ${INPUT}:

    echo Detecting crop parameters....
    CROP=$(mplayer ${INPUT} -benchmark -nosound -vf cropdetect=63:0 -vo null \
        -ao null -ss ${SS} -endpos ${ENDPOS} 2>&1 \
        | awk -F '[(=)]' '/crop=/ {print $3}' \
        | tail -1)
      
    echo Encoding ${INPUT} to ${OUTPUT}:
    for PASS in 1 2
    do
        mencoder ${INPUT} -ovc x264 -x264encopts \
        pass=${PASS}:bitrate=${VBITRATE}:subq=6:partitions=all:8x8dct:me=umh:frameref=5:bframes=3:b_pyramid=normal:weight_b \
        -vf pp=lb,crop=${CROP},scale=${WIDTH}:${HEIGHT},harddup -nosub \
        -oac mp3lame -lameopts br=${ABITRATE}:cbr:aq=0:padding=2 \
        -aid 128 -af resample=${SAMPLE}:0:2 -srate ${SAMPLE} \
        -ofps ${FPS} -sws 9 -o output.avi "$@"
    done

    mplayer output.avi -dumpaudio
    mv stream.dump audio.mp3

    normalize-mp3 audio.mp3
    
    mkvmerge -o ${OUTPUT} -A output.avi audio.mp3

    rm output.avi audio.mp3 divx2pass.log*
done
