#!/bin/sh

################################################################################
# vob2avi - convert all VOB files in directory to MKV                          #
# v0.1.8                                                                       #
# David RC Dayton <2014>                                                       #
################################################################################
#                                   NOTE: requires mplayer/mencoder/mkvtoolnix #
################################################################################

WIDTH="720"
HEIGHT="480"
VBITRATE="800"
ABITRATE="128"
FPS="24000/1001"
SAMPLE="44100"
SS="60"
ENDPOS="180"
ASPECT="16/9"

for FILE in *.vob
do
    BASE=$(echo ${FILE} | awk -F '.' '{print $1}')
    INPUT=${BASE}.vob
    OUTPUT=${BASE}.mkv
    echo Processing ${INPUT}:

    echo Detecting crop parameters....
    CROP=$(mplayer ${INPUT} -benchmark -nosound -vf cropdetect=63:0 -vo null \
        -ao null -ss ${SS} -endpos ${ENDPOS} 2>&1 \
        | awk -F '[(=)]' '/crop=/ {print $3}' \
        | tail -1)
      
    echo Encoding ${INPUT} to ${OUTPUT}:
    for PASS in 1 2
    do
        mencoder ${INPUT} -ovc x264 -x264encopts \
        pass=${PASS}:bitrate=${VBITRATE}:subq=6:partitions=all:8x8dct:me=umh:frameref=5:bframes=3:b_pyramid=normal:weight_b \
        -vf pp=lb,crop=${CROP},scale=${WIDTH}:${HEIGHT},harddup -nosub \
        -oac mp3lame -lameopts br=${ABITRATE}:cbr:aq=0:padding=2 \
        -aid 128 -af volnorm,resample=${SAMPLE}:0:2 -srate ${SAMPLE} \
        -ofps ${FPS} -sws 9 -aspect ${ASPECT} -o output.avi "$@"
    done

    mkvmerge -o ${OUTPUT} output.avi

    rm output.avi divx2pass.log*
done
